#import <PEGKit/PKParser.h>
#import <CoreLocation/CoreLocation.h>

enum {
    ASSIGNSTATEMENT_TOKEN_KIND_STAR = 14,
    ASSIGNSTATEMENT_TOKEN_KIND_AMPERSAND,
    ASSIGNSTATEMENT_TOKEN_KIND_FORWARD_SLASH,
    ASSIGNSTATEMENT_TOKEN_KIND_PLUS,
    ASSIGNSTATEMENT_TOKEN_KIND_CARET,
    ASSIGNSTATEMENT_TOKEN_KIND_COMMA,
    ASSIGNSTATEMENT_TOKEN_KIND_OPEN_PAREN,
    ASSIGNSTATEMENT_TOKEN_KIND_MINUS,
    ASSIGNSTATEMENT_TOKEN_KIND_CLOSE_PAREN,
    ASSIGNSTATEMENT_TOKEN_KIND_PERCENT,
};

@interface AssignStatementParser : PKParser <CLLocationManagerDelegate>

@end

