#import <PEGKit/PKParser.h>

enum {
    EXPRESSIONACTIONPARSER_TOKEN_KIND_COMMA = 14,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_MINUS,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_GE,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_DOT,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_LT,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_NE,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_FORWARD_SLASH,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_EQUALS,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_YES_UPPER,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_OR,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_GT,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_LE,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_AND,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_PERCENT,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_YES,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_AMPERSAND,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_NO,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_CARET,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_OPEN_PAREN,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_NO_UPPER,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_CLOSE_PAREN,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_STAR,
    EXPRESSIONACTIONPARSER_TOKEN_KIND_PLUS,
};

@interface ExpressionActionParser : PKParser

@end

